apiVersion: v1
kind: ConfigMap
metadata:
  name: kps-tasks-api-config
  namespace: kps-tasks
data:
  APP_NAME: "KPS Tasks API"
  APP_ENV: "production"
  LOG_LEVEL: "INFO"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "kps_tasks_db"
