apiVersion: v1
kind: Service
metadata:
  name: kps-tasks-api
  namespace: kps-tasks
spec:
  type: NodePort
  selector:
    app: kps-tasks-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
